### ISSUE TITLE
Client/Device ID Question

### ISSUE THREAD

**Issue by impala454** [tget4/nexx-garage-sdk#1]
Hi, I'm very interested in using this, however don't follow the instructions for getting the client and/or device ID.  I see the link to the Charles Proxy software, however when you get to the Android portion it states: `This means that you can only use SSL Proxying with apps that you control.`.  Since Nexx garage's devices are controlled only with the app, I don't see how I could use that software to obtain the IDs needed.  Any guidance would be appreciated, this looks very cool!

**Comment by tget4** [comment]
Hmm that is interesting. I don't have an Android so I'm not really sure what the best way to set up Charles proxy. I only suggested Charles proxy because I'm familiar with it. Wonder if there is way to do this using an android emulator on a computer. The main thing is just being able to intercept a request and find client_id and device_token.
