### ISSUE TITLE
using SDK within homebridge

### ISSUE THREAD

**Issue by rogbott** [tget4/nexx-garage-sdk#2]
I am using this on an iOS device and it would be awesome to be able to use Nexx with HomeKit. I have Homebridge setup and I am able to get the client ID and the device ID, but for the life of me I can't get the JS to work correctly. I am not super familiar with JS, but when I copy the code into my config.json I get a parsing error before the "import" line. Assuming this works with Homebridge, should this go under the accessories or platform? Do you have a sample snippet of what it should look like? I am super excited to get this working if possible. Thanks so much!

**Comment by tget4** [comment]
You're getting a parsing error because it's expecting config.json to be json and you pasted javascript code.

You'd need to create a custom homebridge plugin, here's an example from their docs: https://github.com/nfarina/homebridge/tree/master/example-plugins/homebridge-samplePlatform

I'm not familiar with creating plugins though. Let me know if you get it working!
